name: 'Image Compression Action'
description: 'Compress images in a pull request and commit changes if compression exceeds the defined threshold'
author: 'Ovis'
branding:
  icon: 'image'
  color: 'blue'
inputs:
  max_quality:
    description: 'Maximum quality for jpegoptim (1-100)'
    required: false
    default: '80'
  compression_threshold:
    description: 'Compression threshold in percentage (default: 30%)'
    required: false
    default: '30'

runs:
  using: "composite"
  steps:
    # コードのチェックアウト
    - name: Checkout code
      uses: actions/checkout@v4

    # 圧縮ツールとbase64を利用するためのツールをインストール
    - name: Install image compression tools
      run: |
        sudo apt-get update
        sudo apt-get install -y jpegoptim optipng coreutils
      shell: bash

    # ベースブランチの取得
    - name: Fetch base branch
      run: |
        git fetch origin "${{ github.base_ref }}" --depth=1
      shell: bash

    # 変更されたファイルを取得し、BASE64エンコードして環境変数に設定
    - name: Check changed files
      id: get_changed_files
      run: |
        git diff --name-only --diff-filter=ACMR "origin/${{ github.base_ref }}"..HEAD > changed_files.txt
        echo "Changed files:"
        cat changed_files.txt
        BASE64_CHANGED=$(base64 -w 0 changed_files.txt)
        echo "changed_files_base64=$BASE64_CHANGED" >> $GITHUB_ENV
        rm -f changed_files.txt
      shell: bash

    # 変更された画像を圧縮
    - name: Compress changed images
      id: compress_images
      shell: bash
      run: |
        echo "Starting image compression..."
        DECODED_FILES=$(echo "${{ env.changed_files_base64 }}" | base64 --decode)
        THRESHOLD=${{ inputs.compression_threshold }}
        ANY_COMPRESSED=false

        while IFS= read -r file; do
          echo "Target file for processing: $file"
          if [[ "$file" == *.jpg || "$file" == *.jpeg || "$file" == *.png ]]; then
            echo "Processing file: $file"
            ORIGINAL_SIZE=$(stat -c%s "$file")
            echo "Original size: $ORIGINAL_SIZE bytes"
            if [[ "$file" == *.jpg || "$file" == *.jpeg ]]; then
              jpegoptim --max=${{ inputs.max_quality }} "$file"
            elif [[ "$file" == *.png ]]; then
              optipng "$file"
            fi
            COMPRESSED_SIZE=$(stat -c%s "$file")
            echo "Compressed size: $COMPRESSED_SIZE bytes"
            if (( (ORIGINAL_SIZE - COMPRESSED_SIZE) * 100 / ORIGINAL_SIZE >= THRESHOLD )); then
              echo "$file compressed by more than ${THRESHOLD}%"
              ANY_COMPRESSED=true
            else
              echo "$file was not compressed by ${THRESHOLD}% or more."
            fi
          else
            echo "Skipping non-image file: $file"
          fi
        done <<< "$DECODED_FILES"

        echo "any_image_compressed=$ANY_COMPRESSED" >> $GITHUB_ENV